version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
  - package-ecosystem: "bundler"
    directory: "/tech-docs"
    schedule:
      interval: "weekly"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
    ignore:
      # Ignore this because updating breaks the tech-docs
      # I am unsure currently what the cause of this is
      - dependency-name: "middleman"
      # Ignore this version of kover-cli"
      - dependency-name: "org.jetbrains.kotlinx:kover-cli"
        versions: [ "1.0.715" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
