FROM stoplight/prism:5


RUN apk add --no-cache curl jq
RUN npm install -g @apidevtools/swagger-cli
RUN mkdir /prismMocks

COPY src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationapi/prismMocks /prismMocks
ADD https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk/v3/api-docs /tmp/adjudications.json
ADD https://dev.moic.service.justice.gov.uk/v3/api-docs.json /prismMocks/manage-pom-case-api.json
ADD https://ministryofjustice.github.io/hmpps-probation-integration-services/tech-docs/projects/external-api-and-delius/api-docs.json /prismMocks/ndelius.json
ADD https://ministryofjustice.github.io/hmpps-probation-integration-services/tech-docs/projects/effective-proposal-framework-and-delius/api-docs.json /prismMocks/probation-integration-epf.json
ADD https://prisoner-search-dev.prison.service.justice.gov.uk/v3/api-docs /tmp/prisoner-offender-search-tmp.json

RUN jq 'del(.components.schemas.Query.properties.subQueries)' /tmp/prisoner-offender-search-tmp.json > /tmp/prisoner-offender-search-tmp1.json
RUN swagger-cli bundle -r -o /prismMocks/prisoner-offender-search.json /tmp/prisoner-offender-search-tmp1.json
RUN swagger-cli bundle -r -o /prismMocks/adjudications.json /tmp/adjudications.json

# new files from this point on need to start with an x- followed by the port number:
ADD https://learningandworkprogress-api-dev.hmpps.service.justice.gov.uk/v3/api-docs /prismMocks/x4020-plp-api.json
ADD https://personal-relationships-api-dev.hmpps.service.justice.gov.uk/v3/api-docs /prismMocks/x4022-personal-relationships.json
RUN sed -i 's/\*\/\*/application\/json/g' /prismMocks/x4021-non-associations.json
RUN sed -i 's/\*\/\*/application\/json/g' /prismMocks/adjudications.json
RUN sed -i 's/\*\/\*/application\/json/g' /prismMocks/assess-risks-and-needs.json
RUN sed -i 's/\*\/\*/application\/json/g' /prismMocks/case-notes.json
RUN sed -i 's/\*\/\*/application\/json/g' /prismMocks/prisoner-offender-search.json
RUN sed -i 's/\*\/\*/application\/json/g' /prismMocks/x4022-personal-relationships.json

ENTRYPOINT sh -c 'port=4010; for file in $(ls /prismMocks/*.json | sort); do node dist/index.js mock -p $port -h 0.0.0.0 $file & port=$((port + 1)); done; wait'
