FROM node:current-alpine3.17

RUN apk update && apk add bash curl --no-cache

RUN curl https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk/v3/api-docs > risk-management-plan-search.json && \
    sed -i "s+\*/\*+application/json+g" risk-management-plan-search.json && \
    npm install -g @stoplight/prism-cli

RUN adduser -D user

USER user

CMD prism mock -p 4091 -h 0.0.0.0 /risk-management-plan-search.json
