FROM node:current-alpine3.17

RUN apk update && apk add bash curl

RUN curl https://ministryofjustice.github.io/hmpps-probation-integration-services/tech-docs/projects/external-api-and-delius/api-docs.json > ndelius-api.json && \
    npm install -g @stoplight/prism-cli

CMD prism mock -p 4010 -h 0.0.0.0 /ndelius-api.json
