FROM node:current-alpine3.17

RUN apk update && apk add bash curl

RUN curl https://ministryofjustice.github.io/hmpps-probation-integration-services/tech-docs/projects/effective-proposal-framework-and-delius/api-docs.json > effective-proposal-framework-and-delius-api.json && \
    npm install -g @stoplight/prism-cli

CMD prism mock -p 4010 -h 0.0.0.0 /effective-proposal-framework-and-delius-api.json