FROM node:current-alpine3.17

RUN apk update && apk add bash

COPY src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationapi/prismMocks/assess-risks-and-needs-api-docs.json /assess-risks-and-needs-api-docs.json

RUN npm install -g @stoplight/prism-cli

RUN adduser -D user

USER user

CMD prism mock -p 4010 -h 0.0.0.0 /assess-risks-and-needs-api-docs.json
