FROM node:current-alpine3.17

RUN apk update && apk add bash curl --no-cache

RUN curl https://prison-api-dev.prison.service.justice.gov.uk/v3/api-docs > prison-api.json && \
    npm install -g @stoplight/prism-cli

RUN adduser -D user

USER user

CMD prism mock -p 4010 -h 0.0.0.0 /prison-api.json
