FROM node:current-alpine3.17

RUN apk update && apk add bash curl

RUN curl https://probation-offender-search-dev.hmpps.service.justice.gov.uk/v3/api-docs > probation-offender-search.json && \
    npm install -g @stoplight/prism-cli

CMD prism mock -p 4010 -h 0.0.0.0 /probation-offender-search.json
