FROM node:current-alpine3.17

RUN apk update && apk add bash curl

COPY /scripts/setup_prisoner_offender_search.sh /setup_prisoner_offender_search.sh

RUN /setup_prisoner_offender_search.sh
RUN npm install -g @stoplight/prism-cli

RUN prism --version

CMD "prism mock -p 4010 -h 0.0.0.0 /prisoner-offender-search.json"
