FROM node:current-alpine3.17

RUN apk update && apk add bash curl --no-cache

COPY src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationapi/prismMocks/probation-offender-search.json /probation-offender-search.json
RUN npm install -g @stoplight/prism-cli

RUN adduser -D user

USER user

CMD prism mock -p 4010 -h 0.0.0.0 /probation-offender-search.json
