FROM node:current-alpine3.17

RUN apk update && apk add bash curl --no-cache

COPY src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationapi/prismMocks/adjudications_api.json /adjudications_api.json

RUN sed -i "s+\*/\*+application/json+g" adjudications_api.json

RUN npm install -g @stoplight/prism-cli

RUN adduser -D user

USER user

CMD prism mock -p 4010 -h 0.0.0.0 /adjudications_api.json
