FROM node:current-alpine3.17

RUN apk update && apk add bash curl

RUN curl https://prisoner-search-dev.prison.service.justice.gov.uk/v3/api-docs > prisoner-offender-search.json && \
    sed -i "s+\*/\*+application/json+g" prisoner-offender-search.json && \
    npm install -g @stoplight/prism-cli

CMD prism mock -p 4010 -h 0.0.0.0 /prisoner-offender-search.json
