FROM node:current-alpine3.17

RUN apk update && apk add bash curl --no-cache

COPY src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsintegrationapi/prismMocks/prisoner-offender-search.json /prisoner-offender-search.json
RUN sed -i 's/\*\/\*/application\/json/g' prisoner-offender-search.json
RUN npm install -g @stoplight/prism-cli

RUN adduser -D user

USER user

CMD prism mock -p 4010 -h 0.0.0.0 /prisoner-offender-search.json
