{{- $config := index .Values "config-override" | default dict -}}
{{- if $config.enabled | default false -}}
{{- if $config.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: yaml-override-config
data:
  override.yaml: |
  {{ $config.data | b64dec }}
{{- end }}
{{- end -}}
