{{- $config := index .Values "config-override" | default dict -}}
{{- if $config.enabled | default false -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: yaml-override-config
data:
  override.yaml: |
    authorisation:
      consumers:
        zkhan:
          roles:
            - "status-only"
  {{- end -}}
