apiVersion: batch/v1
kind: CronJob
metadata:
  name: heartbeat-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 999
          containers:
            - name: heartbeat
              image: ghcr.io/ministryofjustice/hmpps-devops-tools:sha-66a32dc
              args:
                - /bin/sh
                - -exc
                - >-
                   echo -n "${CERT}" > /tmp/client.pem &&
                   echo -n "${KEY}" > /tmp/client.key &&
                   curl ${SERVICE_URL} -H "x-api-key: ${API_KEY}" --cert /tmp/client.pem --key /tmp/client.key |grep firstName &&
                   echo $?
              envFrom:
                - secretRef:
                    name: heartbeat
          restartPolicy: Never
