package uk.gov.justice.digital.hmpps.hmppsintegrationapi.models.locationsInsidePrison

import java.time.LocalDateTime

data class LIPLocation(
  val id: String,
  val prisonId: String,
  val code: String,
  val pathHierarchy: String,
  val locationType: String,
  val localName: String?,
  val comments: String?,
  val permanentlyInactive: Boolean,
  val permanentlyInactiveReason: String?,
  val capacity: LIPLocationCapacity?,
  val oldWorkingCapacity: Int?,
  val certification: LIPLocationCertification?,
  val usage: List<LIPLocationUsageItem>?,
  val accommodationTypes: List<String>?,
  val specialistCellTypes: List<String>?,
  val usedFor: List<String>?,
  val status: String?,
  val convertedCellType: String?,
  val otherConvertedCellType: String?,
  val active: Boolean,
  val deactivatedByParent: Boolean,
  val deactivatedDate: String,
  val deactivatedReason: String?,
  val deactivationReasonDescription: String?,
  val deactivatedBy: String?,
  val proposedReactivationDate: String,
  val planetFmReference: String?,
  val topLevelId: String,
  val level: Int,
  val leafLevel: Boolean,
  val parentId: String?,
  val parentLocation: String?,
  val inactiveCells: Int?,
  val numberOfCellLocations: Int?,
  val childLocations: List<LIPLocation>?,
  val changeHistory: List<LIPChangeHistoryItem>?,
  val transactionHistory: List<LIPTransactionHistoryItem>?,
  val lastModifiedBy: String,
  val lastModifiedDate: LocalDateTime,
  val key: String,
  val isResidential: Boolean,
)
