package uk.gov.justice.digital.hmpps.hmppsintegrationapi.models.locationsInsidePrison

import uk.gov.justice.digital.hmpps.hmppsintegrationapi.models.hmpps.Location
import java.time.LocalDateTime

data class LIPLocation(
  val id: String,
  val prisonId: String,
  val code: String,
  val pathHierarchy: String,
  val locationType: String,
  val localName: String?,
  val comments: String?,
  val permanentlyInactive: Boolean,
  val permanentlyInactiveReason: String?,
  val capacity: LIPLocationCapacity?,
  val oldWorkingCapacity: Int?,
  val certification: LIPLocationCertification?,
  val usage: List<LIPLocationUsageItem>?,
  val accommodationTypes: List<String>?,
  val specialistCellTypes: List<String>?,
  val usedFor: List<String>?,
  val status: String?,
  val convertedCellType: String?,
  val otherConvertedCellType: String?,
  val active: Boolean,
  val deactivatedByParent: Boolean,
  val deactivatedDate: String,
  val deactivatedReason: String?,
  val deactivationReasonDescription: String?,
  val deactivatedBy: String?,
  val proposedReactivationDate: String,
  val planetFmReference: String?,
  val topLevelId: String,
  val level: Int,
  val leafLevel: Boolean,
  val parentId: String?,
  val parentLocation: String?,
  val inactiveCells: Int?,
  val numberOfCellLocations: Int?,
  val childLocations: List<LIPLocation>?,
  val changeHistory: List<LIPChangeHistoryItem>?,
  val transactionHistory: List<LIPTransactionHistoryItem>?,
  val lastModifiedBy: String,
  val lastModifiedDate: LocalDateTime,
  val key: String,
  val isResidential: Boolean,
) {
  fun toLocation(): Location =
    Location(
      key = this.key,
      code = this.code,
      pathHierarchy = this.pathHierarchy,
      locationType = this.locationType,
      localName = this.localName,
      comments = this.comments,
      permanentlyInactive = this.permanentlyInactive,
      permanentlyInactiveReason = this.permanentlyInactiveReason,
      capacity = this.capacity?.toLocationCapacity(),
      oldWorkingCapacity = this.oldWorkingCapacity,
      certification = this.certification?.toLocationCertification(),
      usage = this.usage?.map { it.toLocationUsageItem() },
      accommodationTypes = this.accommodationTypes,
      specialistCellTypes = this.specialistCellTypes,
      usedFor = this.usedFor,
      status = this.status,
      convertedCellType = this.convertedCellType,
      otherConvertedCellType = this.otherConvertedCellType,
      active = this.active,
      deactivatedByParent = this.deactivatedByParent,
      deactivatedDate = this.deactivatedDate,
      deactivatedReason = this.deactivatedReason,
      deactivationReasonDescription = this.deactivationReasonDescription,
      deactivatedBy = this.deactivatedBy,
      proposedReactivationDate = this.proposedReactivationDate,
      planetFmReference = this.planetFmReference,
      topLevelId = this.topLevelId,
      level = this.level,
      parentId = this.parentId,
      parentLocation = this.parentLocation,
      inactiveCells = this.inactiveCells,
      numberOfCellLocations = this.numberOfCellLocations,
      childLocations = this.childLocations?.map { it.toLocation() },
      lastModifiedBy = this.lastModifiedBy,
      lastModifiedDate = this.lastModifiedDate,
      isResidential = this.isResidential,
    )
}
