services:
  int-api:
    base-url: https://dev.integration-api.hmpps.service.justice.gov.uk
  prison-api:
    base-url: https://prison-api-dev.prison.service.justice.gov.uk
  prisoner-offender-search:
    base-url: https://prisoner-search-dev.prison.service.justice.gov.uk
  ndelius:
    base-url: https://external-api-and-delius-dev.hmpps.service.justice.gov.uk
  assess-risks-and-needs:
    base-url: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk
  probation-integration-epf:
    base-url: https://external-api-and-delius-dev.hmpps.service.justice.gov.uk
  adjudications:
    base-url: https://manage-adjudications-api-dev.hmpps.service.justice.gov.uk
  create-and-vary-licence:
    base-url: https://create-and-vary-a-licence-api-test2.hmpps.service.justice.gov.uk
  case-notes:
    base-url: https://dev.offender-case-notes.service.justice.gov.uk
  manage-pom-case-api:
    base-url: https://dev.moic.service.justice.gov.uk
  plp:
    base-url: https://learningandworkprogress-api-dev.hmpps.service.justice.gov.uk
  san:
    base-url: https://support-for-additional-needs-api-dev.hmpps.service.justice.gov.uk
  non-associations:
    base-url: https://non-associations-api-dev.hmpps.service.justice.gov.uk
  personal-relationships:
    base-url: https://personal-relationships-api-dev.hmpps.service.justice.gov.uk
  manage-prison-visits:
    base-url: https://hmpps-manage-prison-visits-orchestration-dev.prison.service.justice.gov.uk
  incentives:
    base-url: https://incentives-api-dev.hmpps.service.justice.gov.uk
  alerts:
    base-url: https://alerts-api-dev.hmpps.service.justice.gov.uk
  hmpps-auth:
    base-url: https://sign-in-dev.hmpps.service.justice.gov.uk
    username: ${CLIENT_ID}
    password: ${CLIENT_SECRET}
  locations-inside-prison:
    base-url: https://locations-inside-prison-api-dev.hmpps.service.justice.gov.uk
  health-and-medication:
    base-url: https://health-and-medication-api-dev.hmpps.service.justice.gov.uk
  activities:
    base-url: https://activities-api-dev.prison.service.justice.gov.uk
  prisoner-base-location:
    base-url: https://prisoner-base-location-api-dev.hmpps.service.justice.gov.uk
  core-person-record:
    base-url: https://hmpps-person-record-dev.hmpps.service.justice.gov.uk

feature-flag:
  # API Config
  course-completion-event-enabled: true
  use-active-alerts-endpoint: true
  use-emergency-contacts-endpoint: true
  use-contact-events-endpoint: true
  csra-endpoint: true
  epf-endpoint-includes-lao: true
  epf-gateway-disabled: true
  cpr-enabled: true
  gateway-cache-enabled: true
  use-webclient-wrapper-for-hmpps-auth: true
  # Events Config
  enable-delete-processed-events: true
  enable-publish-pending-events: true
  enable-domain-events-queue-listener: true
  enable-subscription-filter-policy-updater: true
  person-languages-changed-notifications-enabled: false
  prisoner-base-location-changed-notifications-enabled: true
  prisoner-merge-notifications-enabled: true
  contact-events-notifications-enabled: true
  limited-access-notifications-enabled: true
  deduplicate-events: true

authorisation:
  consumers:
    mapps:
      notes: "See client list in Confluence"
      roles:
        - "mappa"
      queueName: "mappssubscriberqueue"
    ctrlo:
      notes: "See client list in Confluence"
      roles:
        - "ctrlo"
      queueName: "ctrlosubscriberqueue"
    moj-pes:
      notes: "See client list in Confluence"
      roles:
        - "moj-prisoner-education"
    kubernetes-health-check-client:
      notes: "Kubernetes cluster automated healthchecks"
      roles:
        - "hmpps-system"
    pnd:
      notes: "See client list in Confluence"
      roles:
        - "police"
      queueName: "pndsubscriberqueue"
    event-service:
      notes: "HMPPS External Events service"
      roles:
        - "hmpps-system"
    mryall:
      roles:
        - "full-access"
    kilco:
      filters:
        prisons:
          - MKI
      roles:
        - "private-prison"
      queueName: "kilcosubscriberqueue"
    meganexus:
      notes: "See client list in Confluence"
      roles:
        - "curious"
      queueName: "plpsubscriberqueue"
    moj-esw:
      notes: "HMPPS Education Skills and Work team"
      roles:
        - "curious"
      queueName: "mojeswsubscriberqueue"
    serco:
      notes: "See client list in Confluence"
      roles:
        - "serco"
    unilink:
      notes: "See client list in Confluence"
      roles:
        - "private-prison"
    prisonerfacing:
      notes: "See client list in Confluence"
      roles:
        - "moj-prisoner-facing"
    abritton:
      roles:
        - "full-access"
    jbetton:
      roles:
        - "full-access"
    smoke-test-full-access:
      notes: "Automated post-deployment smoke tests (happy path)"
      roles:
        - "full-access"
    smoke-test-limited-access:
      notes: "Automated post-deployment smoke tests (some access denied)"
      roles:
        - "private-prison"
    smoke-test-no-access:
      notes: "Automated post-deployment smoke tests (all access denied)"
      roles:
    test:
      notes: "Used for testing queues in dev"
      roles:
        - "mappa"
      queueName: "testclientsubscriberqueue"
    sleach:
      notes: "https://peoplefinder.service.gov.uk/people/steve-leach"
      roles:
        - "full-access"
    pmcphee:
      roles:
        - "curious"
    geoamey:
      notes: "See client list in Confluence"
      roles:
        - "prisoner-escort-custody-service"
    zkhan:
      roles:
        - "full-access"
    socrates:
      notes: "See client list in Confluence"
      roles:
        - "prisoner-finance"
      filters:
        prisons:
          - MKI
    unify:
      notes: "See client list in Confluence"
      roles:
        - "prisoner-finance"
      filters:
        prisons:
          - MKI
    smoke-test-revoke:
      notes: "Automated post-deployment smoke tests (certificate revocation path)"
      roles:
        - "status-only"
    smartinbox:
      notes: "See client list in Confluence"
      roles:
        - "smartinbox"
    cats:
      notes: "See client list in Confluence"
      roles:
        - "cats"
      queueName: "catssubscriberqueue"
    jwylde:
      roles:
        - "full-access-lao-redactions"
      filters:
        prisons:
          - MKI
          - MDI
    community-payback-dev:
      notes: "Role for developers in the Community Payback team"
      roles:
        - "community-payback"
    daso:
      notes: "See client list in Confluence"
      roles:
        - "daso"
      queueName: "dasosubscriberqueue"
    community-campus:
      notes: "See client list in Confluence"
      roles:
        - "community-payback"
    enhanced-reception-checks:
      notes: "See client list in Confluence"
      roles:
        - "enhanced-reception-checks"
    bmadley:
      notes: "Used to test subscription filter policy"
      roles:
        - "status-only"
      queueName: "bmadleysubscriberqueue"
    synalogik:
      notes: "See client list in Confluence"
      roles:
        - "synalogik"

hmpps.sqs:
  queues:
    hmppsdomainqueue:
      queueName: ${HMPPS_DOMAIN_QUEUE_NAME}
      queueArn: ${HMPPS_DOMAIN_QUEUE_ARN}
      dlqName: ${HMPPS_DOMAIN_DL_QUEUE_NAME}
      subscribeTopicId: domainevents
    mappssubscriberqueue:
      queueName: ${MAPPS_QUEUE_NAME}
      queueArn: ${MAPPS_QUEUE_ARN}
      subscribeTopicId: integrationeventtopic
    plpsubscriberqueue:
      queueName: ${PLP_QUEUE_NAME}
      queueArn: ${PLP_QUEUE_ARN}
      subscribeTopicId: integrationeventtopic
    pndsubscriberqueue:
      queueName: ${PND_QUEUE_NAME}
      queueArn: ${PND_QUEUE_ARN}
      subscribeTopicId: integrationeventtopic
    bmadleysubscriberqueue:
      queueName: ${BMADLEY_QUEUE_NAME}
      queueArn: ${BMADLEY_QUEUE_ARN}
      subscribeTopicId: integrationeventtopic
    testclientsubscriberqueue:
      queueName: ${TEST_CLIENT_QUEUE_NAME}
      queueArn: ${TEST_CLIENT_QUEUE_ARN}
      subscribeTopicId: integrationeventtopic
    kilcosubscriberqueue:
      queueName: ${KILCO_QUEUE_NAME}
      queueArn: ${KILCO_QUEUE_ARN}
      subscribeTopicId: integrationeventtopic
    catssubscriberqueue:
      queueName: ${CATS_QUEUE_NAME}
      queueArn: ${CATS_QUEUE_ARN}
      subscribeTopicId: integrationeventtopic
    mojeswsubscriberqueue:
      queueName: ${MOJ_ESW_QUEUE_NAME}
      queueArn: ${MOJ_ESW_QUEUE_ARN}
      subscribeTopicId: integrationeventtopic
    ctrlosubscriberqueue:
      queueName: ${CTRLO_QUEUE_NAME}
      queueArn: ${CTRLO_QUEUE_ARN}
      subscribeTopicId: integrationeventtopic
    dasosubscriberqueue:
      queueName: ${DASO_QUEUE_NAME}
      queueArn: ${DASO_QUEUE_ARN}
      subscribeTopicId: integrationeventtopic
