package uk.gov.justice.digital.hmpps.hmppsintegrationapi.models.hmpps

import io.swagger.v3.oas.annotations.media.Schema
import java.net.URL
import java.util.UUID

/**
 * A request object describing a change of status to a person's Education.
 */
data class EducationStatusChangeRequest(
  @Schema(description = "The current status of the Assessments", example = "EDUCATION_STARTED")
  val status: EducationStatus = EducationStatus.EDUCATION_UPDATED,
  @jakarta.validation.constraints.NotNull(message = "A detailURL must be provided")
  @Schema(description = "The URL of where to get the person's current Education", example = "https://example.com/sequation-virtual-campus2-api/learnerEducation/A1234AB")
  val detailUrl: URL,
  @jakarta.validation.constraints.NotNull(message = "A requestId must be provided")
  @Schema(description = "A unique request identifier generated by the consumer to allow for tracing requests through the various systems.", example = "0650ba37-a977-4fbe-9000-4715aaecadba")
  val requestId: UUID,
)

enum class EducationStatus {
  EDUCATION_STARTED,
  EDUCATION_COMPLETED,
  EDUCATION_UPDATED,
}
