package uk.gov.justice.digital.hmpps.hmppsintegrationapi.models.hmpps

import io.swagger.v3.oas.annotations.media.Schema
import java.net.URL
import java.util.UUID

/**
 * A request object describing a change of status to a person's Education Additional Learning Needs Assessment .
 */
data class EducationALNAssessmentsChangeRequest(
  @Schema(description = "The current status of the Assessments", example = "ASSESSMENT_COMPLETED")
  val status: ALNStatus = ALNStatus.ASSESSMENT_COMPLETED,
  @jakarta.validation.constraints.NotNull(message = "A detailURL must be provided")
  @Schema(description = "The URL of where to get the person's current ALN assessment details", example = "https://example.com/sequation-virtual-campus2-api/learnerAssessments/v2/A1234AB")
  val detailUrl: URL,
  @jakarta.validation.constraints.NotNull(message = "A requestId must be provided")
  @Schema(description = "A unique request identifier generated by the consumer to allow for tracing requests through the various systems.", example = "0650ba37-a977-4fbe-9000-4715aaecadba")
  val requestId: UUID,
)

enum class ALNStatus {
  ASSESSMENT_COMPLETED,
}
