package uk.gov.justice.digital.hmpps.hmppsintegrationapi.models.hmpps

import java.time.LocalDateTime

data class Location(
  val key: String,
  val code: String,
  val pathHierarchy: String,
  val locationType: String,
  val localName: String?,
  val comments: String?,
  val permanentlyInactive: Boolean,
  val permanentlyInactiveReason: String?,
  val capacity: LocationCapacity?,
  val oldWorkingCapacity: Int?,
  val certification: LocationCertification?,
  val usage: List<LocationUsageItem>?,
  val accommodationTypes: List<String>?,
  val specialistCellTypes: List<String>?,
  val usedFor: List<String>?,
  val status: String?,
  val convertedCellType: String?,
  val otherConvertedCellType: String?,
  val active: Boolean,
  val deactivatedByParent: Boolean,
  val deactivatedDate: String,
  val deactivatedReason: String?,
  val deactivationReasonDescription: String?,
  val deactivatedBy: String?,
  val proposedReactivationDate: String,
  val planetFmReference: String?,
  val topLevelId: String,
  val level: Int,
  val parentId: String?,
  val parentLocation: String?,
  val inactiveCells: Int?,
  val numberOfCellLocations: Int?,
  val childLocations: List<Location>?,
  val lastModifiedBy: String,
  val lastModifiedDate: LocalDateTime,
  val isResidential: Boolean,
)
