package uk.gov.justice.digital.hmpps.hmppsintegrationapi.models.hmpps

enum class UpstreamApi {
  NOMIS,
  PRISONER_OFFENDER_SEARCH,
  PROBATION_OFFENDER_SEARCH,
  NDELIUS,
  ASSESS_RISKS_AND_NEEDS,
  EFFECTIVE_PROPOSAL_FRAMEWORK,
  ADJUDICATIONS,
  CVL,
  CASE_NOTES,
  MANAGE_POM_CASE,
  RISK_MANAGEMENT_PLAN,
  TEST,
  PLP,
  NON_ASSOCIATIONS,
  PERSONAL_RELATIONSHIPS,
  MANAGE_PRISON_VISITS,
  INCENTIVES,
  PRISONER_ALERTS,
}
