#version: 2.1
#orbs:
#  hmpps: ministryofjustice/hmpps@8
#  slack: circleci/slack@4.12.1
#  shellcheck: circleci/shellcheck@3
#  aws-cli: circleci/aws-cli@4.0.0
#  aws-ecr: circleci/aws-ecr@8.2.1
#parameters:
#  releases-slack-channel:
#    type: string
#    default: hmpps-integration-api-alerts
#  java-options:
#    type: string
#    default: -Xmx2g -XX:MaxMetaspaceSize=1g -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process -Dorg.gradle.workers.max=1
#slack-fail-post-step:
#  post-steps:
#    - slack/notify:
#        event: fail
#        branch_pattern: main
#        channel: << pipeline.parameters.alerts-slack-channel >>
#        custom: |
#          {
#            "blocks": [
#              {
#                "type": "header",
#                "text": {
#                  "type": "plain_text",
#                  "text": ":this-is-fine-fire: ${CIRCLE_JOB} job has failed",
#                  "emoji": true
#                }
#              },
#              {
#                "type": "context",
#                "elements": [
#                  {
#                    "type": "mrkdwn",
#                    "text": "Project: *${CIRCLE_PROJECT_REPONAME}*"
#                  },
#                  {
#                    "type": "mrkdwn",
#                    "text": "Branch: *${CIRCLE_BRANCH}*"
#                  },
#                  {
#                    "type": "mrkdwn",
#                    "text": "Build: *#${CIRCLE_BUILD_NUM}*"
#                  }
#                ]
#              },
#              {
#                "type": "actions",
#                "elements": [
#                  {
#                    "type": "button",
#                    "text": { "type": "plain_text", "text": "View job" },
#                    "url": "${CIRCLE_BUILD_URL}"
#                  }
#                ]
#              }
#            ]
#          }
#jobs:
#  lint-code:
#    executor:
#      name: hmpps/java
#      tag: "21.0"
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#            - gradle-{{ checksum "build.gradle.kts" }}
#            - gradle-
#      - run:
#          name: Lint code
#          command: make lint
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: gradle-{{ checksum "build.gradle.kts" }}
#  unit-tests:
#    executor:
#      name: hmpps/java
#      tag: "21.0"
#      java_options: << pipeline.parameters.java-options >>
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#            - gradle-{{ checksum "build.gradle.kts" }}
#            - gradle-
#      - run:
#          name: Run unit tests
#          command: make unit-test
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: gradle-{{ checksum "build.gradle.kts" }}
#      - store_test_results:
#          path: build/reports/tests/unitTest
#      - store_artifacts:
#          path: build/reports/tests/unitTest
#  integration-tests:
#    machine:
#      image: ubuntu-2204:2022.10.2
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#            - gradle-{{ checksum "build.gradle.kts" }}
#            - gradle-
#      - run:
#          name: Install OpenJDK 21
#          command: |
#            sudo apt-get update && sudo apt-get install openjdk-21-jdk
#            sudo update-alternatives --set java /usr/lib/jvm/java-21-openjdk-amd64/bin/java
#            sudo update-alternatives --set javac /usr/lib/jvm/java-21-openjdk-amd64/bin/javac
#            java -version
#      - run:
#          name: Run integration tests
#          command: make integration-test
#      - store_test_results:
#          path: build/reports/tests/integrationTest
#      - store_artifacts:
#          path: build/reports/tests/integrationTest
#  create-and-push-image-to-ecr:
#    docker:
#      - image: ministryofjustice/cloud-platform-tools
#    steps:
#      - checkout
#      - setup_remote_docker:
#          docker_layer_caching: true
#      - run:
#          name: Build application Docker image
#          command: make build
#      - hmpps/create_app_version
#      - aws-cli/setup:
#          role_arn: $ECR_ROLE_TO_ASSUME
#          region: AWS_DEFAULT_REGION
#      - deploy:
#          name: Push application Docker image
#          command: make publish
#  smoke-tests-dev:
#    docker:
#      - image: grafana/k6:1.0.0
#    steps:
#      - checkout
#      - run:
#          name: Run smoke tests
#          command: |
#            k6 run ./scripts/K6/full-access-smoke-tests.js
#            k6 run ./scripts/K6/limited-access-smoke-tests.js
#            k6 run ./scripts/K6/no-access-with-certs-smoke-tests.js
#            k6 run ./scripts/K6/no-access-without-certs-smoke-tests.js
#  smoke-tests-higher-envs:
#    docker:
#      - image: grafana/k6:1.0.0
#    steps:
#      - checkout
#      - run:
#          name: Run smoke tests
#          command: |
#            k6 run ./scripts/K6/smoke-tests-higher-envs.js
#workflows:
#  version: 2
