package uk.gov.justice.digital.hmpps.hmppsintegrationapi.events.enums

enum class IntegrationEventType(
  val pathTemplate: String,
) {
  DYNAMIC_RISKS_CHANGED(
    "v1/persons/{hmppsId}/risks/dynamic",
  ),
  PROBATION_STATUS_CHANGED(
    "v1/persons/{hmppsId}/status-information",
  ),
  MAPPA_DETAIL_CHANGED(
    "v1/persons/{hmppsId}/risks/mappadetail",
  ),
  RISK_SCORE_CHANGED(
    "v1/persons/{hmppsId}/risks/scores",
  ),
  PRISONER_BASE_LOCATION_CHANGED(
    "v1/persons/{hmppsId}/prisoner-base-location",
  ),
  KEY_DATES_AND_ADJUSTMENTS_PRISONER_RELEASE(
    "v1/persons/{hmppsId}/sentences/latest-key-dates-and-adjustments",
  ),
  LICENCE_CONDITION_CHANGED(
    "v1/persons/{hmppsId}/licences/conditions",
  ),
  RISK_OF_SERIOUS_HARM_CHANGED(
    "v1/persons/{hmppsId}/risks/serious-harm",
  ),
  PLP_INDUCTION_SCHEDULE_CHANGED(
    "v1/persons/{nomisNumber}/plp-induction-schedule/history",
  ),
  PLP_REVIEW_SCHEDULE_CHANGED(
    "v1/persons/{nomisNumber}/plp-review-schedule",
  ),
  SAN_PLAN_CREATION_SCHEDULE_CHANGED(
    "v1/persons/{nomisNumber}/education/san/plan-creation-schedule",
  ),
  SAN_REVIEW_SCHEDULE_CHANGED(
    "v1/persons/{nomisNumber}/education/san/review-schedule",
  ),
  PERSON_STATUS_CHANGED(
    "v1/persons/{hmppsId}",
  ),
  PERSON_ADDRESS_CHANGED(
    "v1/persons/{hmppsId}/addresses",
  ),
  PERSON_CONTACTS_CHANGED(
    "v1/persons/{hmppsId}/contacts",
  ),
  PERSON_IEP_LEVEL_CHANGED(
    "v1/persons/{hmppsId}/iep-level",
  ),
  PERSON_VISITOR_RESTRICTIONS_CHANGED(
    "v1/persons/{hmppsId}/visitor/{contactId}/restrictions",
  ),
  PERSON_VISIT_RESTRICTIONS_CHANGED(
    "v1/persons/{hmppsId}/visit-restrictions",
  ),
  PERSON_VISIT_ORDERS_CHANGED(
    "v1/persons/{hmppsId}/visit-orders",
  ),
  PERSON_FUTURE_VISITS_CHANGED(
    "v1/persons/{hmppsId}/visit/future",
  ),
  PERSON_ALERTS_CHANGED(
    "v1/persons/{hmppsId}/alerts",
  ),
  PERSON_PND_ALERTS_CHANGED(
    "v1/pnd/persons/{hmppsId}/alerts",
  ),
  PERSON_CASE_NOTES_CHANGED(
    "v1/persons/{hmppsId}/case-notes",
  ),
  PERSON_NAME_CHANGED(
    "v1/persons/{hmppsId}/name",
  ),
  PERSON_CELL_LOCATION_CHANGED(
    "v1/persons/{hmppsId}/cell-location",
  ),
  PERSON_RISK_CATEGORIES_CHANGED(
    "v1/persons/{hmppsId}/risks/categories",
  ),
  PERSON_SENTENCES_CHANGED(
    "v1/persons/{hmppsId}/sentences",
  ),
  PERSON_OFFENCES_CHANGED(
    "v1/persons/{hmppsId}/offences",
  ),
  PERSON_RESPONSIBLE_OFFICER_CHANGED(
    "v1/persons/{hmppsId}/person-responsible-officer",
  ),
  PERSON_PROTECTED_CHARACTERISTICS_CHANGED(
    "v1/persons/{hmppsId}/protected-characteristics",
  ),
  PERSON_REPORTED_ADJUDICATIONS_CHANGED(
    "v1/persons/{hmppsId}/reported-adjudications",
  ),
  PERSON_NUMBER_OF_CHILDREN_CHANGED(
    "v1/persons/{hmppsId}/number-of-children",
  ),
  PERSON_PHYSICAL_CHARACTERISTICS_CHANGED(
    "v1/persons/{hmppsId}/physical-characteristics",
  ),
  PERSON_IMAGES_CHANGED(
    "v1/persons/{hmppsId}/images",
  ),
  PERSON_IMAGE_CHANGED(
    "v1/persons/{hmppsId}/images/{imageId}",
  ),
  PRISONERS_CHANGED(
    "v1/prison/prisoners",
  ),
  PRISONER_CHANGED(
    "v1/prison/prisoners/{hmppsId}",
  ),
  PERSON_EDUCATION_ASSESSMENTS_CHANGED(
    "v1/persons/{hmppsId}/education/assessments",
  ),
  PRISONER_BALANCES_CHANGED(
    "v1/prison/{prisonId}/prisoners/{hmppsId}/balances",
  ),
  PRISONER_ACCOUNT_BALANCES_CHANGED(
    "v1/prison/{prisonId}/prisoners/{hmppsId}/accounts/{accountCode}/balances",
  ),
  PRISONER_ACCOUNT_TRANSACTIONS_CHANGED(
    "v1/prison/{prisonId}/prisoners/{hmppsId}/accounts/{accountCode}/transactions",
  ),
  PRISONER_NON_ASSOCIATIONS_CHANGED(
    "v1/prison/{prisonId}/prisoners/{hmppsId}/non-associations",
  ),
  PRISON_VISITS_CHANGED(
    "v1/prison/{prisonId}/visit/search",
  ),
  PRISON_RESIDENTIAL_HIERARCHY_CHANGED(
    "v1/prison/{prisonId}/residential-hierarchy",
  ),
  PRISON_LOCATION_CHANGED(
    "v1/prison/{prisonId}/location/{locationKey}",
  ),
  PRISON_RESIDENTIAL_DETAILS_CHANGED(
    "v1/prison/{prisonId}/residential-details",
  ),
  PRISON_CAPACITY_CHANGED(
    "v1/prison/{prisonId}/capacity",
  ),
  VISIT_CHANGED(
    "v1/visit/{visitReference}",
  ),
  VISIT_FROM_EXTERNAL_SYSTEM_CREATED(
    "v1/visit/id/by-client-ref/{clientVisitReference}",
  ),
  CONTACT_CHANGED(
    "v1/contacts/{contactId}",
  ),
  CONTACT_EVENT_CREATED(
    "v1/persons/{hmppsId}/contact-events/{contactEventId}",
  ),
  CONTACT_EVENT_CHANGED(
    "v1/persons/{hmppsId}/contact-events/{contactEventId}",
  ),
  PERSON_HEALTH_AND_DIET_CHANGED(
    "v1/persons/{hmppsId}/health-and-diet",
  ),
  PERSON_CARE_NEEDS_CHANGED(
    "v1/persons/{hmppsId}/care-needs",
  ),
  PERSON_LANGUAGES_CHANGED(
    "v1/persons/{hmppsId}/languages",
  ),
  PRISONER_MERGED(
    "v1/persons/{hmppsId}",
  ),
  PERSON_ACCESS_LIMITATIONS_CHANGED(
    "v1/persons/{hmppsId}/access-limitations",
  ),
}
