apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmpps-integration-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hmpps-integration-api-app
  template:
    metadata:
      labels:
        app: hmpps-integration-api-app
    spec:
      containers:
        - name: hmpps-integration-api-app
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/hmpps-integration-api-team/hmpps-integration-api-development-ecr:latest
          ports:
            - containerPort: 8080
          env:
            - name: TOPSECRET
              valueFrom:
                secretKeyRef:
                  name: top-secret
                  key: password
