apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <ingress-name>
  namespace: <namespace-name>
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: <ingress-name>-<namespace-name>-<colour>
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: default
  tls:
    - hosts:
      - helloworld-rubyapp.apps.live.cloud-platform.service.justice.gov.uk
  rules:
  - host: helloworld-rubyapp.apps.live.cloud-platform.service.justice.gov.uk
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: rubyapp-service
              port:
                number: 4567
