apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hmpps-integration-api
  namespace: hmpps-integration-api-development
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: hmpps-integration-api-hmpps-integration-api-development-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: default
  tls:
    - hosts:
      - hmpps-integration-api-development.apps.live.cloud-platform.service.justice.gov.uk
  rules:
  - host: hmpps-integration-api-development.apps.live.cloud-platform.service.justice.gov.uk
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: hmpps-integration-api-service
              port:
                number: 8080
