apiVersion: v1
kind: Service
metadata:
  name: hmpps-integration-api-service
  labels:
    app: hmpps-integration-api-service
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: hmpps-integration-api-app
