@startuml context

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

skinparam linetype polyline

title HMPPS Integration API - Context Diagram

AddElementTag("not_yet_implemented", $bgColor="#D3D3D3", $fontColor="#9C9C9C")

System_Ext(consumer, "Consumer Application", "An authenticated consumer of the Integration API.")

Boundary(moj, "Ministry of Justice (MoJ)", "Ministerial Department") {
  Boundary(hmpps, "His Majesty's Prison and Probation Service (HMPPS)", "Executive Agency") {
    System(hmpps_integration_api, "Integration API", "A single point of entry for services to retrieve data from multiple HMPPS systems.")

    SystemQueue_Ext(messaging, "Messaging System", "SNS/SQS Service.",$tags="not_yet_implemented")

    System_Ext(upstream, "Upstream Systems", "Integrated systems where data is retrieved from.")
  }
}

Rel_Down(consumer, hmpps_integration_api, "Uses")
Rel_Right(hmpps_integration_api, messaging, "Posts updates")
Rel_Up(messaging, consumer, "Retrieves updates")
Rel(hmpps_integration_api, upstream, "Queries for data")

SHOW_DYNAMIC_LEGEND()

@enduml
