@startuml container-aws

   !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

   title HMPPS Integration API - Container Diagram for connectivity with the API

   AddRelTag("mTLS", $textColor=$ARROW_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DottedLine())

   Boundary(home_office, "Home Office", "Ministerial Department") {
      System_Ext(mapps, "Multi-Agency Public Protection Service (MAPPS)", "A service that will replace the Violent and Sex Offender Register (ViSOR).")
   }

   Boundary(other_organisation, "Any other organisation") {
      System_Ext(external_system, "External System", "Any service that requires data from HMPPS systems e.g. another ministerial department or public body.")
   }

   Boundary(hmpps, "His Majesty's Prison and Probation Service (HMPPS)", "Executive Agency") {
      Boundary(cloudplatform, "Cloud Platform", "Elastic Kubernetes Service"){
         System(hmpps_integration_api, "Integration API", "A single point of entry for services to retrieve data from multiple HMPPS systems.")
      }

      Boundary(aws, "Amazon Web Services", "AWS"){
         System(route53, "Route 53", "DNS record for our domain.")
         System(apigateway, "API Gateway", "Routes traffic to internal Kubernetes Ingress URL")
         System(s3, "S3 Truststore", "Authorised client certificate storage")
      }
   }

   Rel_Right(mapps, route53, "Uses", "HTTPS", $link="https://development.integration-api.hmpps.service.justice.gov.uk/")
   Rel_Right(external_system, route53, "Uses", "HTTPS", $link="https://development.integration-api.hmpps.service.justice.gov.uk/")
   Rel_Down(route53, apigateway, "Forwards integration requests to")
   BiRel_Right(mapps, apigateway, "Certificate exchange", "mTLS", $tags="mTLS")
   Rel_Right(apigateway, hmpps_integration_api, "Forwards requests")
   Rel_Down(apigateway, s3, "Checks certificates against")

   SHOW_DYNAMIC_LEGEND()

@enduml