package uk.gov.justice.digital.hmpps.hmppsintegrationapi.roles

import uk.gov.justice.digital.hmpps.hmppsintegrationapi.roles.dsl.role

val privatePrison =
  role("private-prison") {
    permissions {
      -"/v1/hmpps/id/by-nomis-number/{nomisNumber}"
      -"/v1/hmpps/id/nomis-number/by-hmpps-id/{hmppsId}"
      -"/v1/persons/{hmppsId}/addresses"
      -"/v1/persons/{hmppsId}/contacts"
      -"/v1/persons/{hmppsId}/iep-level"
      -"/v1/persons/{hmppsId}/visitor/{contactId}/restrictions"
      -"/v1/persons/{hmppsId}/visit-restrictions"
      -"/v1/persons/{hmppsId}/visit-orders"
      -"/v1/persons/{hmppsId}/visit/future"
      -"/v1/persons/{hmppsId}/alerts"
      -"/v1/persons/{hmppsId}/case-notes"
      -"/v1/persons/{hmppsId}/name"
      -"/v1/persons/{hmppsId}/cell-location"
      -"/v1/persons/{hmppsId}/risks/categories"
      -"/v1/persons/{hmppsId}/sentences"
      -"/v1/persons/{hmppsId}/sentences/latest-key-dates-and-adjustments"
      -"/v1/persons/{hmppsId}/offences"
      -"/v1/persons/{hmppsId}/person-responsible-officer"
      -"/v1/persons/{hmppsId}/protected-characteristics"
      -"/v1/persons/{hmppsId}/reported-adjudications"
      -"/v1/persons/{hmppsId}/number-of-children"
      -"/v1/persons/{hmppsId}/physical-characteristics"
      -"/v1/persons/{hmppsId}/images"
      -"/v1/persons/{hmppsId}/images/{id}"
      -"/v1/prison/prisoners"
      -"/v1/prison/prisoners/{hmppsId}"
      -"/v1/prison/{prisonId}/prisoners/{hmppsId}/balances"
      -"/v1/prison/{prisonId}/prisoners/{hmppsId}/accounts/{accountCode}/balances"
      -"/v1/prison/{prisonId}/prisoners/{hmppsId}/accounts/{accountCode}/transactions"
      -"/v1/prison/{prisonId}/prisoners/{hmppsId}/transactions/{clientUniqueRef}"
      -"/v1/prison/{prisonId}/prisoners/{hmppsId}/transactions"
      -"/v1/prison/{prisonId}/prisoners/{hmppsId}/non-associations"
      -"/v1/prison/{prisonId}/visit/search"
      -"/v1/prison/{prisonId}/residential-hierarchy"
      -"/v1/prison/{prisonId}/location/{key}"
      -"/v1/prison/{prisonId}/residential-details"
      -"/v1/prison/{prisonId}/capacity"
      -"/v1/prison/{prisonId}/prison-regime"
      -"/v1/prison/{prisonId}/appointments/search"
      -"/v1/activities/{activityId}/schedules"
      -"/v1/activities/schedule/{scheduleId}"
      -"/v1/activities/schedule/{scheduleId}/suitability-criteria"
      -"/v1/prison/{prisonId}/activities"
      -"/v1/prison/{prisonId}/prison-pay-bands"
      -"/v1/visit/{visitReference}"
      -"/v1/visit"
      -"/v1/visit/id/by-client-ref/{clientReference}"
      -"/v1/visit/{visitReference}/cancel"
      -"/v1/contacts/{contactId}"
      -"/v1/prison/{prisonId}/location/{key}/deactivate"
      -"/v1/persons/{hmppsId}/health-and-diet"
      -"/v1/persons/{hmppsId}/care-needs"
      -"/v1/persons/{hmppsId}/languages"
      -"/v1/persons/{hmppsId}/education"
      -"/v1/activities/schedule/attendance"
      -"/v1/activities/attendance-reasons"
      -"/v1/activities/schedule/{scheduleId}/deallocate"
      -"/v1/prison/{prisonId}/prisoners/{hmppsId}/scheduled-instances"
      -"/v1/activities/deallocation-reasons"
      -"/v1/activities/schedule/{scheduleId}/allocate"
      -"/v1/prison/prisoners/{hmppsId}/activities/attendances"
      -"/v1/activities/schedule/{scheduleId}/waiting-list-applications"
      -"/v1/persons/{hmppsId}/risks/serious-harm"
      -"/v1/status"
    }
  }
