package uk.gov.justice.digital.hmpps.hmppsintegrationapi.roles

import uk.gov.justice.digital.hmpps.hmppsintegrationapi.roles.dsl.role

val privatePrison =
  role("private-prison") {
    permissions {
      -"/v1/hmpps/id/by-nomis-number/[^/]*$"
      -"/v1/hmpps/id/nomis-number/by-hmpps-id/[^/]*$"
      -"/v1/persons/.*/addresses"
      -"/v1/persons/.*/contacts[^/]*$"
      -"/v1/persons/.*/iep-level"
      -"/v1/persons/.*/visitor/.*/restrictions"
      -"/v1/persons/.*/visit-restrictions"
      -"/v1/persons/.*/visit-orders"
      -"/v1/persons/.*/visit/future"
      -"/v1/persons/.*/alerts"
      -"/v1/persons/.*/case-notes"
      -"/v1/persons/.*/name"
      -"/v1/persons/.*/cell-location"
      -"/v1/persons/.*/risks/categories"
      -"/v1/persons/.*/sentences"
      -"/v1/persons/.*/sentences/latest-key-dates-and-adjustments"
      -"/v1/persons/.*/offences"
      -"/v1/persons/.*/person-responsible-officer"
      -"/v1/persons/.*/protected-characteristics"
      -"/v1/persons/.*/reported-adjudications"
      -"/v1/persons/.*/number-of-children"
      -"/v1/persons/.*/physical-characteristics"
      -"/v1/persons/.*/images"
      -"/v1/persons/.*/images/.*"
      -"/v1/prison/prisoners"
      -"/v1/prison/prisoners/[^/]*$"
      -"/v1/prison/.*/prisoners/[^/]*/balances$"
      -"/v1/prison/.*/prisoners/.*/accounts/.*/balances"
      -"/v1/prison/.*/prisoners/.*/accounts/.*/transactions"
      -"/v1/prison/.*/prisoners/.*/transactions/[^/]*$"
      -"/v1/prison/.*/prisoners/.*/transactions"
      -"/v1/prison/.*/prisoners/.*/non-associations"
      -"/v1/prison/.*/visit/search[^/]*$"
      -"/v1/prison/.*/residential-hierarchy"
      -"/v1/prison/.*/location/[^/]*$"
      -"/v1/prison/.*/residential-details"
      -"/v1/prison/.*/capacity"
      -"/v1/prison/.*/prison-regime"
      -"/v1/prison/.*/appointments/search"
      -"/v1/activities/.*/schedules"
      -"/v1/activities/schedule/[^/]*$"
      -"/v1/activities/schedule/.*/suitability-criteria"
      -"/v1/prison/.*/activities"
      -"/v1/prison/.*/prison-pay-bands"
      -"/v1/visit/[^/]*$"
      -"/v1/visit"
      -"/v1/visit/id/by-client-ref/[^/]*$"
      -"/v1/visit/.*/cancel"
      -"/v1/contacts/[^/]*$"
      -"/v1/prison/.*/location/.*/deactivate"
      -"/v1/persons/.*/health-and-diet"
      -"/v1/persons/.*/care-needs"
      -"/v1/persons/.*/languages"
      -"/v1/persons/.*/education"
      -"/v1/activities/schedule/attendance"
      -"/v1/activities/attendance-reasons"
      -"/v1/activities/schedule/.*/deallocate"
      -"/v1/prison/.*/.*/scheduled-instances"
      -"/v1/activities/deallocation-reasons"
      -"/v1/activities/schedule/.*/allocate"
      -"/v1/prison/prisoners/.*/activities/attendances"
      -"/v1/activities/schedule/.*/waiting-list-applications"
      -"/v1/status"
    }
  }
