---
# Per environment values which override defaults in hmpps-integration-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-integration-api-dev.apps.live.cloud-platform.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/auth-tls-secret: "hmpps-integration-api-dev/client-certificate-auth"

  poddisruptionbudget:
    enabled: false

  env:
    SPRING_PROFILES_ACTIVE: dev
    SENTRY_ENVIRONMENT: dev

  namespace_secrets:
    hmpps-auth:
      CLIENT_ID: "client-id"
      CLIENT_SECRET: "client-secret"
    other-services:
      APPINSIGHTS_INSTRUMENTATIONKEY: "azure-app-insights"
      SENTRY_DSN: "sentry"
    cp-course-completion-events-secret:
      HMPPS_SQS_QUEUES_EDUCATIONCOURSECOMPLETIONEVENTS_QUEUE_NAME: "sqs_queue_name"
    event-test-client-queue:
      TEST_CLIENT_QUEUE_NAME: "sqs_name"
      TEST_CLIENT_QUEUE_ARN: "sqs_arn"
    event-bmadley-queue:
      BMADLEY_QUEUE_NAME: "sqs_name"
      BMADLEY_QUEUE_ARN: "sqs_arn"
      BMADLEY_FILTER_POLICY_SECRET_ID: "bmadley_filter_policy_secret_id"
    event-kilco-queue:
      KILCO_QUEUE_NAME: "sqs_name"
      KILCO_QUEUE_ARN: "sqs_arn"
      KILCO_FILTER_POLICY_SECRET_ID: "kilco_filter_policy_secret_id"
    event-moj-esw-queue:
      MOJ_ESW_QUEUE_NAME: "sqs_name"
      MOJ_ESW_QUEUE_ARN: "sqs_arn"
    event-daso-queue:
      DASO_QUEUE_NAME: "sqs_name"
      DASO_QUEUE_ARN: "sqs_arn"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-integration-api-alerts
  sqsAlertsQueueNames:
    - "book-a-prison-visit-dev-hmpps_prison_visits_write_events_queue"
    - "book-a-prison-visit-dev-hmpps_prison_visits_write_events_dlq"
    - "locations-inside-prison-development-update_from_external_system_events_queue"
    - "locations-inside-prison-development-update_from_external_system_events_dlq"
    - "activities-and-appointments-dev-update_from_external_system_events_queue"
    - "activities-and-appointments-dev-update_from_external_system_events_dlq"
  sqsAlertsOldestThreshold: 60
  sqsAlertsTotalMessagesThreshold: 10
  ingressAlertsEnabled: false
