DROP TABLE IF EXISTS EVENT_NOTIFICATION;

CREATE TABLE EVENT_NOTIFICATION(
    EVENT_ID SERIAL PRIMARY KEY,
    HMPPS_ID varchar(15),
    EVENT_TYPE varchar(20),
    URL varchar(200),
    LAST_MODIFIED_DATETIME TIMESTAMP NOT NULL
);

COMMENT ON TABLE EVENT_NOTIFICATION IS 'Holds HMPPS event list in temporary store to reduce duplicate messages';

CREATE UNIQUE INDEX LAST_MODIFIED_DATETIME ON EVENT_NOTIFICATION (LAST_MODIFIED_DATETIME);

