name: Format code
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  format-code:
    if: github.actor != 'dependabot[bot]' && !startsWith(github.head_ref, 'dependabot')
    name: 🧹 Format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Format code
        uses: ./.github/actions/format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
