name: Generate OpenAPI spec

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-openapi-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - name: Serve dependencies
        run: make serve-dependencies
      - name: Start service
        run: |
          ./gradlew bootRun &
          timeout 300 sh -c 'until curl -s localhost:8080/v3/api-docs; do sleep 5; done'
        env:
          SPRING_PROFILES_ACTIVE: local
      - name: Fetch API docs
        run: mkdir -p openapi && curl -f localhost:8080/v3/api-docs -o openapi/api-docs.json
      - name: Publish API docs
        uses: JamesIves/github-pages-deploy-action@920cbb300dcd3f0568dbc42700c61e2fd9e6139c # v4.6.4
        with:
          folder: openapi
          target-folder: openapi
