name: Load Test
on:
  workflow_dispatch:
    inputs:
      duration:
        default: "1"
        description: Number of seconds for the test to run
        required: true
        type: string
      requests_per_second:
        default: "5"
        description: Number of concurrent requests per second
        required: true
        type: string
jobs:
  dev-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run main Smoke Test script
        shell: bash
        env:
          DURATION: ${{ inputs.duration }}
          RPS: ${{ inputs.requests_per_second }}
          PROFILE: MAIN
          HMPPSID: X688624
          DOMAIN: dev.integration-api.hmpps.service.justice.gov.uk
          CERT: "${{ secrets.DEV_SMOKE_TEST_FULL_ACCESS_CERT }}"
          PRIVATE_KEY: "${{ secrets.DEV_SMOKE_TEST_FULL_ACCESS_KEY }}"
          API_KEY: "${{ secrets.DEV_SMOKE_TEST_FULL_ACCESS_API_KEY }}"
        run: |
          k6 run --summary-mode=full --quiet ./scripts/K6/load-tests.js
