name: Load Test
on:
  push:
    branches:
      - HIA-916-test-api-gw-usage-plan
  workflow_dispatch:
jobs:
  dev-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run main Smoke Test script
        shell: bash
        env:
          PROFILE: DEV_10_RPS_20_SECONDS
          DOMAIN: dev.integration-api.hmpps.service.justice.gov.uk
          CERT: "${{ secrets.DEV_SMOKE_TEST_FULL_ACCESS_CERT }}"
          PRIVATE_KEY: "${{ secrets.DEV_SMOKE_TEST_FULL_ACCESS_KEY }}"
          API_KEY: "${{ secrets.DEV_SMOKE_TEST_FULL_ACCESS_API_KEY }}"
        run: |
          k6 run --summary-mode=full --quiet ./scripts/K6/load-tests.js
