name: Production Smoke Test
on:
  workflow_call:
jobs:
  prod-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup K6
        uses: grafana/setup-k6-action@db07bd9765aac508ef18982e52ab937fe633a065 # v1
      - name: Run minimal Smoke Test script
        shell: bash
        env:
          PROFILE: MINIMAL
          HMPPSID:
          DOMAIN: integration-api.hmpps.service.justice.gov.uk
          CERT: "${{ secrets.PROD_SMOKE_TEST_CERT }}"
          PRIVATE_KEY: "${{ secrets.PROD_SMOKE_TEST_KEY }}"
          API_KEY: "${{ secrets.PROD_SMOKE_TEST_API_KEY }}"
        run: |
          k6 run --summary-mode=full --quiet ./scripts/K6/smoke-tests.js
      - name: Run no cert test
        shell: bash
        env:
          PROFILE: NOPERMS
          DOMAIN: integration-api.hmpps.service.justice.gov.uk
        run: |
          k6 run --summary-mode=full --quiet ./scripts/K6/smoke-tests.js
  prod-send-failure-to-slack:
    runs-on: ubuntu-latest
    needs:
      - prod-smoke-tests
    if:
      always()
    steps:
      - name: Send failure message to Slack
        uses: slackapi/slack-github-action@03ea5433c137af7c0495bc0cad1af10403fc800c # v3.0.2
        if: ${{ contains(needs.*.result, 'failure') }}
        with:
          method: chat.postMessage
          token: ${{ secrets.HMPPS_SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "hmpps-integration-api-alerts",
              "text": "Prod smoke tests have failed",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❌ Prod smoke tests failure"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "The production smoke tests have failed. Please check the logs and re-run the workflow."
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Logs"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
