name: Development Smoke Test
on:
  workflow_call:
jobs:
  dev-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup K6
        uses: grafana/setup-k6-action@db07bd9765aac508ef18982e52ab937fe633a065 # v1
      - name: Run main Smoke Test script
        shell: bash
        env:
          PROFILE: MAIN
          HMPPSID: X688624
          DOMAIN: dev.integration-api.hmpps.service.justice.gov.uk
          CERT: "${{ secrets.DEV_SMOKE_TEST_FULL_ACCESS_CERT }}"
          PRIVATE_KEY: "${{ secrets.DEV_SMOKE_TEST_FULL_ACCESS_KEY }}"
          API_KEY: "${{ secrets.DEV_SMOKE_TEST_FULL_ACCESS_API_KEY }}"
        run: |
          k6 run --summary-mode=full --quiet ./scripts/K6/smoke-tests.js
      - name: Run no access test
        shell: bash
        env:
          PROFILE: NOPERMS
          HMPPSID: X688624
          DOMAIN: dev.integration-api.hmpps.service.justice.gov.uk
          CERT: "${{ secrets.DEV_SMOKE_TEST_NO_ACCESS_CERT }}"
          PRIVATE_KEY: "${{ secrets.DEV_SMOKE_TEST_NO_ACCESS_KEY }}"
          API_KEY: "${{ secrets.DEV_SMOKE_TEST_NO_ACCESS_API_KEY }}"
        run: |
          k6 run --summary-mode=full --quiet ./scripts/K6/smoke-tests.js
      - name: Run partial access test
        shell: bash
        env:
          PROFILE: PARTIAL
          HMPPSID: X688624
          DOMAIN: dev.integration-api.hmpps.service.justice.gov.uk
          CERT: "${{ secrets.DEV_SMOKE_TEST_LIMITED_ACCESS_CERT }}"
          PRIVATE_KEY: "${{ secrets.DEV_SMOKE_TEST_LIMITED_ACCESS_KEY }}"
          API_KEY: "${{ secrets.DEV_SMOKE_TEST_LIMITED_ACCESS_API_KEY }}"
        run: |
          k6 run --summary-mode=full --quiet ./scripts/K6/smoke-tests.js
      - name: Run no cert test
        shell: bash
        env:
          PROFILE: NOPERMS
          HMPPSID: X688624
          DOMAIN: dev.integration-api.hmpps.service.justice.gov.uk
        run: |
          k6 run --summary-mode=full --quiet ./scripts/K6/smoke-tests.js
      - name: Run revoked cert test
        shell: bash
        env:
          PROFILE: NOPERMS
          HMPPSID: X688624
          DOMAIN: dev.integration-api.hmpps.service.justice.gov.uk
          CERT: "${{ secrets.DEV_SMOKE_TEST_REVOKED_CERT }}"
          PRIVATE_KEY: "${{ secrets.DEV_SMOKE_TEST_REVOKED_KEY }}"
          API_KEY: "${{ secrets.DEV_SMOKE_TEST_REVOKED_API_KEY }}"
        run: |
          k6 run --summary-mode=full --quiet ./scripts/K6/smoke-tests.js
  dev-send-failure-to-slack:
    runs-on: ubuntu-latest
    needs:
      - dev-smoke-tests
    if:
      always()
    steps:
      - name: Send failure message to Slack
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        if: ${{ contains(needs.*.result, 'failure') }}
        with:
          method: chat.postMessage
          token: ${{ secrets.HMPPS_SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "hmpps-integration-api-alerts",
              "text": "Dev smoke tests have failed",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❌ Dev smoke tests failure"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "The development smoke tests have failed. Please check the logs and re-run the workflow."
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Logs"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
