name: Preprod Smoke Test
on:
  push:
    branches:
      - HIA-1458-check-waf-response-body
  workflow_call:
jobs:
  preprod-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup K6
        uses: grafana/setup-k6-action@db07bd9765aac508ef18982e52ab937fe633a065 # v1
      - name: Run minimal Smoke Test script
        shell: bash
        env:
          PROFILE: MINIMAL
          HMPPSID:
          DOMAIN: preprod.integration-api.hmpps.service.justice.gov.uk
          CERT: "${{ secrets.PREPROD_SMOKE_TEST_CERT }}"
          PRIVATE_KEY: "${{ secrets.PREPROD_SMOKE_TEST_KEY }}"
          API_KEY: "${{ secrets.PREPROD_SMOKE_TEST_API_KEY }}"
        run: |
          k6 run --summary-mode=full --quiet ./scripts/K6/smoke-tests.js
      - name: Run no cert test
        shell: bash
        env:
          PROFILE: NOPERMS
          DOMAIN: preprod.integration-api.hmpps.service.justice.gov.uk
        run: |
          k6 run --summary-mode=full --quiet ./scripts/K6/smoke-tests.js
  preprod-send-failure-to-slack:
    runs-on: ubuntu-latest
    needs:
      - preprod-smoke-tests
    if:
      always()
    steps:
      - name: Send failure message to Slack
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        if: ${{ contains(needs.*.result, 'failure') }}
        with:
          method: chat.postMessage
          token: ${{ secrets.HMPPS_SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "hmpps-integration-api-alerts",
              "text": "Preprod smoke tests have failed",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "❌ Preprod smoke tests failure"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "The pre-production smoke tests have failed. Please check the logs and re-run the workflow."
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Logs"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
