name: Test2

on:
  push:
    branches:
      - 'HIA-1388_parallel_test_poc'
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # V7.0.0
      - name: Setup Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # V5
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Serve Dependencies
        id: dependencies
        run: make serve-dependencies
        background: true
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: Build code
        id: build
        run: ./gradlew compileKotlin
      - name: Run ktlintCheck
        id: lint
        run: ./gradlew ktlintCheck
        background: true
      - name: Run unit tests
        id: unittest
        run: ./gradlew unittest
        background: true
      - name: Wait for dependencies
        wait: [ dependencies ]
      - name: Run Integration Tests
        run: ./gradlew integrationTest
        background: true
      - name: Wait for background steps
        wait-all:

#      - name: Run detekt
#        run: ./gradlew detekt
#        background: true
#      - name: Run Unit Tests
#        shell: bash
#        run: TEST_TYPE="UNIT" ./gradlew koverBinaryReport
#        background: true
#      - name: Serve Dependencies
#        run: make serve-dependencies
#        background: true
#      - name: Run Integration Tests
#        run: TEST_TYPE="INT" ./gradlew koverXmlReport
#        background: true
#        wait: Serve Dependencies


